### ISSUE TITLE
Make member static

### ISSUE THREAD

**Issue by wmjordan** [u2uconsult/codeanalyzers#9] opened 2017-11-07 02:07 UTC
The following code was defined as an instance member, changing it to static can improve performance for performance-sensitive code:
````C#
private void Act() {
    Global<ILogger>.Get().Log("Act"); // Global<ILogger> was a static type
}
````

**Comment by KrisVandermotten** [comment] 2017-11-08 08:16
That code should trigger U2U1002, unless it is used in a delegate constructor (see the [documentation](https://github.com/u2uconsult/codeanalyzers/blob/master/docs/U2U1002.md) for details). Does it not?

**Comment by wmjordan** [comment] 2017-11-08 14:32
It is weird. Sometimes `U2U1002` was not triggered.
My previous sample was too small.

Please take a look at the following badly designed class, which happened to reflect the issue:
The last `Grow(Program)` method could be declared `static`, but `1002` was not triggered.

````C#
sealed class Program
{
	static void Main(string[] args) {
		var p = new Program() { Id = 1 };
		Console.WriteLine("My bro is " + p.Grow().Id.ToString());
	}

	public int Id { get; set; }

	public Program Grow() {
		Console.WriteLine("I am " + Id.ToString());
		return Grow(this);
	}
	Program Grow(Program program) {
		return new Program() { Id = program.Id + 1 };
	}
}
````

**Comment by KrisVandermotten** [comment] 2017-11-08 15:38
That is indeed a case that is overlooked by the current analyzer. Thanks for reporting it.

It will be fixed in version 2.9.1

**Comment by KrisVandermotten** [comment] 2017-11-09 20:39
Version 2.9.1 is available now. Can you confirm the issue is resolved?

**Comment by wmjordan** [comment] 2017-11-10 06:20
For the above code sample, yes.
In another class in a more complex project, the issue has not been fixed yet.
I'll try to construct a simpler sample for you later.

**Comment by wmjordan** [comment] 2017-11-10 06:35
I found another situation where the analyzer could not work properly.
The private method `M` could be declared `static`. If you remove the `partial class C` part, the analyzer was working fine. With the `partial`, the analyzer `U2U1002` no longer worked.

````C#
partial class C
{
	public int MyProperty { get; set; }
}
sealed partial class C
{
	internal object M() { return M(1, true); }
	private object M(int node, bool dummy) {
		return null;
	}
}
````

**Comment by KrisVandermotten** [comment] 2017-11-10 18:39
I can not reproduce that. Pasting that code in a unit test yields the following message:

    Test.cs(8,17): warning U2U1002: Method C.M(int, bool) may be declared static

**Comment by wmjordan** [comment] 2017-11-11 07:52
It is strange.

I did not paste the code in a unit test project.
I created a new console app project, targeting at .net framework 4.0, and paste the above code to the program.cs file, overwriting everything in it. No warning was presented.
I am using VS 2017 with the latest update.

**Comment by KrisVandermotten** [comment] 2017-11-11 10:52
I did the same, and the warning appears.

Can you check one thing? In Options > Text Editor > C# > Advanced, is ["Enable full solution analysis"](https://docs.microsoft.com/nl-be/visualstudio/code-quality/how-to-enable-and-disable-full-solution-analysis-for-managed-code) turned on or not? If not, what happens when you turn it on?

**Comment by wmjordan** [comment] 2017-11-11 11:19
That option was off for performance considerations.
I put those two parts of the "partial" class at the same code file, as the above code showed, the warning did not show up still.

**Comment by KrisVandermotten** [comment] 2017-11-13 13:13
I'm sorry, but I cannot reproduce that. I'm going to close this issue, as the original bug was fixed.

**Closed as completed by KrisVandermotten** 2017-11-13 13:13 UTC
Labels: bug
